### ISSUE TITLE
Gateway durations are unstable

### ISSUE THREAD

**Issue by Johannason** [Shadows-of-Fire/GatewaysToEternity#1]
The first gateway placed, functions just fine.  
After that first gateway is completed, later placing another gateway in the same location causes the new gateway to spawn its first wave of enemies, and then instantly close.  
Subsequent gateways have unpredictable durations, sometimes playing out in full, sometimes spontaneously closing right after spawning a wave (without producing the experience bounty).

**Comment by Johannason** [comment]
It seems the arena rooms I was building were not large enough. With a larger battleground, this no longer occurs.

**Comment by Shadows-of-Fire** [comment]
Yeah, something I should write down is failure to spawn a mob results in immediate termination of the gate
