### ISSUE TITLE
Is it possible to give a floor limit for the door?

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/GatewaysToEternity#10]
I found that building a tall pillar on the ground, just the right height to let the monster fall down and drop a lot of blood and will not destroy the door.

Or the monster is born with a slow landing,

**Comment by Shadows-of-Fire** [comment]
what 🤔

**Comment by alin529** [comment]
https://user-images.githubusercontent.com/94986399/197409738-966341bf-bcfe-43c1-a23c-01e0a212cc7b.mp4

**Comment by ghost** [comment]
Is it possible to make changes to this situation? For example so that they can land slowly.

https://user-images.githubusercontent.com/94986399/197409792-2ab85983-105c-49e5-8547-f87e7aff75f1.mp4

**Comment by Shadows-of-Fire** [comment]
Ah, yeah.  I should either apply slow fall to them or search for the ground and spawn them there.

As a stop-gap you could pre-apply slow falling to all the entities, but it would be a bit cumbersome.

**Comment by Shadows-of-Fire** [comment]
Entities will no longer spawn midair starting in 2.1.5

**Comment by H8Craft** [comment]
this fix may have caused a new issue, when i make a gate mobs spawn at all y levels no matter the distance, mobs are never all on the same level when they spawn making every wave scatter to the lowest and highest y levels, its un playable.
