### ISSUE TITLE
Space required for a gate is finicky

### ISSUE THREAD

**Issue by Partonetrain** [Shadows-of-Fire/GatewaysToEternity#13]
Using GatewaysToEternity-1.18.2-2.1.5.jar, gateways can be awfully finicky about the space required. I'm using the default gateway data, and, judging based on the GIF on the CurseForge page, this should be plenty of space. I've had gate pearls work and not work in the exact same spot for no discernible reason. Is there something I'm missing?
https://user-images.githubusercontent.com/19861808/200195863-1197aa8f-1f23-44db-ae47-dd9effd7ae5d.mp4

edit: no idea what's up with the video's resolution but it still gets the point across

**Comment by Shadows-of-Fire** [comment]
There appears to be some issue with the new floor-finding function and flat surfaces which is making it locate invalid spawn targets.  I'll have to see what's up.

**Comment by Shadows-of-Fire** [comment]
Fixed in 3.1.0
