### ISSUE TITLE
loot_table reward crashes multiplayer server

### ISSUE THREAD

**Issue by DuraBrite** [Shadows-of-Fire/GatewaysToEternity#15]
**Version:** GatewaysToEternity-1.16.5-1.0.0

**Description:**
I created a custom gate and added the following reward-entry for a wave:

```
{
  "type": "loot_table",
  "loot_table": "minecraft:chests/simple_dungeon",
  "rolls": 1
}
```

In Singleplayer this works without any issues. But using this on a multiplayer server, the server instantly crashes when trying to drop the reward.

**Crash-Report:** https://hastebin.com/jicapuleco.http

**Comment by Shadows-of-Fire** [comment]
The crash report is not available, and 1.16.5 is not a supported version
