### ISSUE TITLE
Gateway reward release speed must adapt to the amount of rewards in queue

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/GatewaysToEternity#16]
Currently, a Large Gate Pearl may take multiple minutes (in extreme cases, almost a full in-game day) to fully release its rewards after players kill the last of the wave mobs. This happens when players accumulate tens of thousands of items in rewards during and after each wave of the gate round.

To reproduce:
1. Give yourself the following sword: `/give @s netherite_sword{Enchantments:[{id:"minecraft:sharpness",lvl:99s},{id:"minecraft:smite",lvl:99s},{id:"minecraft:looting",lvl:9s}]} 1`
2. Summon a (preferably large) gate pearl.
3. Using the sword from the command in step 1, kill the mobs in the gate wave by wave until the gate is successfully completed.
4. Notice that rewards from the gate keep being released for as many as 5-10 minutes after the last of the mobs are killed.

Originally reproduced in ATM8 1.0.4 (Minecraft 1.19.2)
Mod version: 3.1.0

(Edit: reduced Looting on original test sword from 99 to 9 as looting 9 (or equivalent) is achievable with Apotheosis and Quark.)

**Comment by Shadows-of-Fire** [comment]
I'll be honest, looting 99 is *not* a valid/legitimate thing that I really want to put time into bandaiding.

Does it happen under "reasonable" conditions?

**Comment by James103** [comment]
<details>

<summary> Setblock command for shulker box containing the sword that reproduced this issue </summary>

```
setblock ~ ~ ~ minecraft:shulker_box[facing=up]{ForgeCaps:{},Items:[{Count:1b,Slot:0b,id:"netherite_sword",tag:{Enchantments:[{id:"minecraft:sharpness",lvl:10s},{id:"minecraft:smite",lvl:11s},{id:"deeperdarker:sculk_smite",lvl:1s},{id:"minecraft:sweeping",lvl:9s},{id:"evilcraft:life_stealing",lvl:6s},{id:"ensorcellation:leech",lvl:8s},{id:"ensorcellation:vorpal",lvl:8s},{id:"minecraft:looting",lvl:9s},{id:"apotheosis:capturing",lvl:7s},{id:"spirit:soul_reaper",lvl:7s},{id:"reliquary:severing",lvl:9s},{id:"ensorcellation:frost_aspect",lvl:5s},{id:"minecolonies:raider_damage_enchant",lvl:6s},{id:"travelanchors:teleportation",lvl:1s},{id:"ensorcellation:soulbound",lvl:1s},{id:"apotheosis:scavenger",lvl:3s}],RepairCost:1,affix_data:{affixes:{"apotheosis:socket":4.0f,"apotheosis:sword/attribute/elongated":0.47894788f,"apotheosis:sword/attribute/graceful":0.74407476f,"apotheosis:sword/attribute/intricate":0.77450854f,"apotheosis:sword/attribute/lacerating":0.22029376f,"apotheosis:sword/mob_effect/sophisticated":0.8402604f,"apotheosis:telepathic":0.45501584f},gems:[{Count:1b,id:"apotheosis:gem",tag:{modifier:{Amount:0.30000001192092896d,Name:"GemBonus_apotheosis:attack_damage",Operation:2,UUID:[I;-1959441858,-1707260023,-1387033478,1772509089],attribute:"minecraft:generic.attack_damage"},purity:1.0f,variant:3}},{Count:1b,id:"apotheosis:gem",tag:{modifier:{Amount:0.30000001192092896d,Name:"GemBonus_apotheosis:attack_damage",Operation:2,UUID:[I;-805395253,270418931,-1229055166,-2113366613],attribute:"minecraft:generic.attack_damage"},purity:1.0f,variant:3}},{Count:1b,id:"apotheosis:gem",tag:{modifier:{Amount:0.30000001192092896d,Name:"GemBonus_apotheosis:attack_damage",Operation:2,UUID:[I;-2110784133,1798588282,-1645606814,-801083966],attribute:"minecraft:generic.attack_damage"},purity:1.0f,variant:3}},{Count:1b,id:"apotheosis:gem",tag:{modifier:{Amount:2.5d,Name:"GemBonus_apotheosis:attack_range",Operation:0,UUID:[I;-880096768,-1887223469,-1623230730,514889304],attribute:"forge:attack_range"},purity:1.0f,variant:8}}],name:'{"color":"#ED7014","translate":"%s %s %s","with":[{"translate":"affix.apotheosis:sword/attribute/graceful"},"",{"translate":"affix.apotheosis:sword/attribute/intricate.suffix"}]}',rarity:"mythic"}}}]}
```

</details>

That sword has Looting 9 instead of Looting 99, but it also has other enchantments from the Apotheosis, Ensorcellation, and Reliquary mods that increase the drop rates.

I also had 44.75 `generic.luck` when this issue was first encountered: `attribute @s generic.luck base set 44.75`
