### ISSUE TITLE
Always one enemy leftr

### ISSUE THREAD

**Issue by Blabliblubpaul** [Shadows-of-Fire/GatewaysToEternity#18]
I am using 1.18, version 2.20 of eternal gateways.
It's included in ftb:Inferno, and i updated the mod manually.
The Problem is, that on most gates, there is always one enemy remaining, even is i can find none in the area around. 
It doesnt' happen ion ghast gates, and i though that this might be happening due to creepers that explode but are not counted as dead?

**Comment by Drulikar** [comment]
Also occurs for us on _every_ bellringer fight (multiplayer server). We've done the fight about four times, each on the modpack's version of eternal gateways, and by updating to this version. So far the update to 2.20 has stopped the spawning of random mobs at the bottom of the nether lava lakes though.

**Comment by Blabliblubpaul** [comment]
yes, the spawning at y=0 has stopped, but the problem is that some enemies are just gone

**Comment by Shadows-of-Fire** [comment]
The only thing that might be able to cause this is the entity changing dimension (but the entity reference not being released, thus not tripping any other mechanisms).

Realistically the fix here is just going to make the gate abort on-time, if the issue is what I think it is.

**Comment by Drulikar** [comment]
I'm not sure how an enemy would be changing dimensions unless you mean they get despawned by getting knocked away into an unloaded chunk maybe - its not like these portals are spawning near nether/end portals. The issue to me seems to be kill reason such as a creeper self exploding, or magic spells that indirectly kill an enemy. If that enemy ceases to exist or runs away (rebounding enchantment from apotheosis might as well be considered a curse) it needs to just decrement the enemy counter and progress the wave.
