### ISSUE TITLE
[1.16.5] Unable to use loot table rewards on server

### ISSUE THREAD

**Issue by RoyalReject** [Shadows-of-Fire/GatewaysToEternity#20]
This was brought up in discord and not sure it you are working on fixes for the 1.16.5 but when using a loot table reward on a dedicated server it crashed the game.

Offending code: https://github.com/Shadows-of-Fire/GatewaysToEternity/blob/1.16/src/main/java/shadows/gateways/gate/Reward.java#L330-L338

gate.getPosition(1); Is client side only

**Comment by Shadows-of-Fire** [comment]
1.16 isn't receiving bugfixes or feature updates at this point
