### ISSUE TITLE
1.18.2: Skeleton gate does not recognize wither skeleton kills as valid when door is used in the Nether.

### ISSUE THREAD

**Issue by border999** [Shadows-of-Fire/GatewaysToEternity#22]
Tried to use the Skeleton gate in the Nether to get it to spawn Wither Skeletons. It worked, however, the gate did not recognize that those skeletons that IT had spawned were valid due to them not being normal skeletons. I do not know how you want to handle this I just felt the need to inform you.

**Comment by Shadows-of-Fire** [comment]
Do you have Wither Skeleton Tweaks installed?  Trying to figure out what is causing the transformation so I can address it properly.

**Comment by border999** [comment]
WitherSkeletonTweaks-1.18.2-7.1.3

**Comment by border999** [comment]
sorry for the late reply, went to the gym for a bit

**Comment by LucidDreamer0322** [comment]
@Shadows-of-Fire 

The AllTheMods8 pack has this mod and WitherSkeletonTweaks so you may have a number of people who are having this issue.

This mod is really cool and would be very helpful, especially with that pack as you need a large number of Wither Bones for the heart canisters, not to mention farming the rare drops for reliquary, but that ATM pack is so loot heavy that the "not dropping bows and swords" is almost mandatory,

Ran some gates in the nether without withertweaks:
    - All skels were regular non-wither ones
    - Gate accepted the kills and processed everything as you'd expect
  
So the conflict definitely seems to be that something in tweaks is forcing the gate to spawn wither skels, which was exactly what I was hoping to happen when I went to the nether to run it.  I need with bones and wanted the skulls for wither farming. :P

Would it fix the incompatibility if you had the gate do a realm check and spawn wither skeles on it's own if the player uses it in the nether?  I think it would be an easy(ish) fix and would still serve the desired function of at least myself and i'd assume most people who run into this issue.

Really cool mod and we appreciate you. <3
