### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by katubug** [Shadows-of-Fire/GatewaysToEternity#25]
Hi, I'm working on a modpack update and kept getting this crash. After some testing, I've isolated that it's the most recent update of this mod causing it. Seems to be a bug with Oculus maybe? I have sickbrain so I can't figure it out.

[crash-2023-05-22_15.36.53-client.txt](https://github.com/Shadows-of-Fire/GatewaysToEternity/files/11536868/crash-2023-05-22_15.36.53-client.txt)

The crash has my modlist and other info, please let me know if I'm forgetting anything important.

**Comment by Shadows-of-Fire** [comment]
That crash looks like the fault of some rendering overhaul mod (oculus / rubidium / etc).  Nothing gateways can do could invoke such an error.  I suggest removing each of those mods until it stops happening, and reporting it to the one which causes it.

**Comment by katubug** [comment]
Thanks, I was just coming back to say that it's happening again and I'm unsure with what. The issue is that none of those have updated since my last successful launch, so it's most likely one of those mods and another mod - now to figure out which. Sorry for the false alarm.
