### ISSUE TITLE
Feature request : preview / description of how much space a gateway needs

### ISSUE THREAD

**Issue by minecraftdudette** [Shadows-of-Fire/GatewaysToEternity#27]
Hello i am really enjoying your mod in the modpack i play. I used the smaller portal of slimes in a big room and all went well. Howerver after being ready for the big gateway and preparing a really cool fighting room, it told me not enough space.

**Comment by SevenChords** [comment]
i second this, same story here, build a separate building to do the gateways in an enclosed space, documentation on how much space is needed for the different gateways really is necessary

**Comment by Shadows-of-Fire** [comment]
Default values have been noted on the curseforge page, and any deviations will be noted on individual pearls as of 4.2.0
