### ISSUE TITLE
Crash 2nd wave Ghast portal

### ISSUE THREAD

**Issue by DomenicoCatrambone** [Shadows-of-Fire/GatewaysToEternity#3]
I think the error is self explanatory:
Attempted to apply a random attribute modifier to an entity (minecraft:ghast) that does not have that attribute (minecraft:generic.attack_damage)!

Crash report:
[crash-2022-08-06_10.51.02-server.txt](https://github.com/Shadows-of-Fire/GatewaysToEternity/files/9274740/crash-2022-08-06_10.51.02-server.txt)

**Comment by Shadows-of-Fire** [comment]
Fixed by Placebo 6.5.1
