### ISSUE TITLE
Gateways that run commands as part of rewards have their commands logged in the chat

### ISSUE THREAD

**Issue by puncrafter** [Shadows-of-Fire/GatewaysToEternity#31]
I'm attempting to have a gateway use a `/summon` command to spawn a special entity as a reward. This is working exactly as intended, except for the fact that it runs the command in the chat, which while not game-breaking, does ruin immersion a bit.

I think a good solution to this problem would be to add an optional argument to the JSON structure that could allow logging commands to chat to be toggleable.

**Comment by Shadows-of-Fire** [comment]
Are you opped (or have cheats enabled in ssp)?  Pretty sure all commands run are logged to operators, but not to normal players.

**Comment by puncrafter** [comment]
I gave it a test, and yes, it does only log commands to operators. While this does slightly inconvenience me as I like to play my worlds with cheats enabled, I can see why it would work this way. Thanks for the help
