### ISSUE TITLE
Medium-sized gate pearls recipes do not work

### ISSUE THREAD

**Issue by LuminaSapphira** [Shadows-of-Fire/GatewaysToEternity#33]
JEI/EMI does not show a recipe for them, and attempting to craft manually yields a broken gate pearl.

The gateway ID in the recipe no longer matches the gateway name in the data pack.

Will submit a PR to fix.

**Comment by grundyboy34** [comment]
Still having this issue on 1.20.1 v 4.1.1
All the normal gateway recipes (8 of the catalyst + eye of ender in the middle) results in "Gate Pearl" with tooltip "Errored Gate Pearl, file a bug report detailing how you obtained this."
This effectively limits players to only using small and large pearls currently.

**Comment by LuminaSapphira** [comment]
That's because pending an overhaul to how gates work the fix hasn't been released yet. It'll be rendered obsolete by changes to gateways soon. In the meantime, here's a (untested) datapack that fixes it: https://drive.google.com/file/d/1I9dATr1JRESc-ahtt4ESgRX0tVhw-oX1/view
