### ISSUE TITLE
Question - Is the mod compatible with `Tom's Simple Storage Mod`?

### ISSUE THREAD

**Issue by Gallucky** [Shadows-of-Fire/GatewaysToEternity#36]
Is this mod compatible with the mod `Tom's Simple Storage Mod`?
I am playing TNP Limitless 7 and I stumbled upon a bug when I crafted `Enderman Gate Pearl`.
I don't know for sure if it is a crafting issue but when I crafted it and put it into the storage network and pulled it out it came back as `'Gated Pearl'`.
So when I tried to use it, it didn't work because it was a generic one.
I reported the issue to the modpack issue page and the dev replied that it sounded like a 'cross mod interaction' between your mod and the other one mentioned previously.
The dev suggested that I ask you and see what you think is the reason for the issue.
Thanks in advance.

**Comment by Shadows-of-Fire** [comment]
The only way that could happen is if for some reason that mod was clearing the nbt data of stored items, which would be quite the bug on their part.  Gate pearls have no specific interactions regarding being in inventories, and they have no interactions in item form whatsoever.  I'm not sure what exactly happened in your case to cause the nbt loss, but it wasn't gateways.
