### ISSUE TITLE
1.16.5 chance tootip is not correct

### ISSUE THREAD

**Issue by 2929762171** [Shadows-of-Fire/GatewaysToEternity#37]
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/98941945/0c7ea005-733d-42b7-9f04-60200abd7b06)
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/98941945/35c996aa-c7fc-45bc-8c0b-4d85640b0c49)

**Comment by Shadows-of-Fire** [comment]
1.16 is not supported
