### ISSUE TITLE
1.16.5 command desc tooltip didn't work

### ISSUE THREAD

**Issue by 2929762171** [Shadows-of-Fire/GatewaysToEternity#38]
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/98941945/db10cb2f-785f-4ced-b820-0c8bf70bf8e7)
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/98941945/8900bcfb-f82f-441b-9f0f-a0ef02513631)

**Comment by Shadows-of-Fire** [comment]
1.16 is not supported
