### ISSUE TITLE
1.16.5 entities nbt didn't work?

### ISSUE THREAD

**Issue by 2929762171** [Shadows-of-Fire/GatewaysToEternity#39]
None of them worked.
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/98941945/298ea3d8-6e28-436b-bb03-975f914a801a)

**Comment by 2929762171** [comment]
None of them worked.
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/98941945/55dc93c0-e9d6-4a29-b889-febfb865ec47)

**Comment by Shadows-of-Fire** [comment]
1.16 is not supported
