### ISSUE TITLE
1.20.1 Small Zombie Gateway not working

### ISSUE THREAD

**Issue by RaidenKoizuma** [Shadows-of-Fire/GatewaysToEternity#40]
Small zombie gateway doesn't spawn any enemies on 1.20.1 version of mod. Not sure what other info you need.

**Comment by RaidenKoizuma** [comment]
This may be an issue with other small gateways, haven't been able to test

**Comment by LazrProductions** [comment]
Im also getting this issue, with all gateways not just zombies.
