### ISSUE TITLE
Errored Gate Pearl

### ISSUE THREAD

**Issue by Crisis4552** [Shadows-of-Fire/GatewaysToEternity#41]
Got a message saying " Errored Gate Pearl , file a bug report detailing how you obtained this." Making mid-tier gateways. Recipes for mid don't show up in JEI either.

**Comment by vainlaind4in** [comment]
same here

**Comment by UsagiKodo** [comment]
mid tier recipe also does not show up for me

**Comment by starfarts** [comment]
Likewise I receive this error

**Comment by Solarleuchte** [comment]
I have this Issue aswell.
See here on YouTube: https://youtu.be/bpKUlpFc1F8
