### ISSUE TITLE
[Issue] Gateway of Overworldian Nights can fail if a creeper explodes

### ISSUE THREAD

**Issue by DinnerBeef** [Shadows-of-Fire/GatewaysToEternity#43]
I don't know whether this is an issue or not. Want to make sure it's not.

### Describe the bug
I'm not sure if this is intended, but if a creeper spawned by this gateway explodes, the gateway quits and pops a chat message "The gateway imploded because an entity was removed without being killed"

Maybe don't spawn creepers or include an exception for them? Unless this is intentional, which I guess I could understand but is kind of dumb IMO.

### Steps to reproduce
Craft said gateway
Use it
Let a creeper explode
Gateway quits

### Expected behavior
Maybe the gateway should continue, since exploding is what creepers do?

Issue From: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4353

**Comment by Shadows-of-Fire** [comment]
Ah, yeah, the rule flag for allow discards should be present on that gate.

**Comment by Shadows-of-Fire** [comment]
2e8bac3b52bebc3f5107dc257ff44c964bc4b44e
