### ISSUE TITLE
Lang not loading

### ISSUE THREAD

**Issue by entyen** [Shadows-of-Fire/GatewaysToEternity#44]
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/31936997/6adc48cd-acd3-42be-969a-28e29c977ab1)

```
{
	"gateways.basic/overworldian_nights": "Overworld Rift Small"
}
```

```
{
  "pack": {
    "pack_format": 4,
    "description": "Custom Gateways for GatewaysToEternity"
  }
}
```

but on load file have name <Gate Pearl - gateways.basic/overworldian_nights>

**Comment by Shadows-of-Fire** [comment]
Anything under `assets/` has to be loaded from a resource pack, not a datapack.
