### ISSUE TITLE
1.20.1/4.2.3 mobs do not spawn from gateways

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/GatewaysToEternity#46]
![2024-01-07_09 51 43](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/123023377/99a6c32c-f173-4bfe-b68c-ddc64981676a)

As per the screenshot in my normal world, I am running modded Minecraft 1.20.1 forge and using Gateways 4.2.3. 

- The spaces I open the portals in are valid
- Mobs do not come out, but particles appear
- I go to my creative world and successfully spawn mobs per round
- I load back into my normal world and get a round complete, but mobs still do not spawn

**Comment by Shadows-of-Fire** [comment]
are you on peaceful?

**Comment by ghost** [comment]
I am on normal difficulty

Edit: I made a new normal world with cheats and spawned a portal item in, mobs appeared in that one.

**Comment by ghost** [comment]
Ok so I found the issue!

The campfire blocks spawns mod from Serilum was blocking the spawns from the gateway. I Realized that after noticing the prior note.
