### ISSUE TITLE
errored gate pearl reward

### ISSUE THREAD

**Issue by wolfbain5** [Shadows-of-Fire/GatewaysToEternity#49]
using ver 4.2.4
It was listed as one of the rewards, but because it said error ed, I chose not to select it. so I dont have a crash report to offer you
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/24768891/0ed46dcf-58c4-44e9-b92b-d82ee35083ad)

**Comment by Shadows-of-Fire** [comment]
You need to report this issue to the individual modpack.
