### ISSUE TITLE
nbt tag and gear_set will not work if the entity has default weapon.

### ISSUE THREAD

**Issue by YumisLink** [Shadows-of-Fire/GatewaysToEternity#50]
## MC Version
1.20.1
## forge Version
47.2.0
## Mod Version
GatewaysToEternity-1.20.1-4.2.4 (lasted in curseforge)

## Question Descript
I tried the following scenarios：
NBT tag and gear_set will not work if the entity has default weapon or armor.

### i  try to spawn a skeleton and with following codes and without any modifiers:
```
"entity": "minecraft:skeleton",
                    "count": 1,
                    "nbt": {
                        "CustomName": "{\"translate\":\"name.xueyuan_wuhao\",\"color\":\"gold\"}",
                        "HandItems": [
                            {
                                "Count": 1,
                                "id": "simplyswords:storms_edge",
                                "tag": {
                                    "Damage": 0
                                }
                            },
                            {
                                "Count": 1,
                                "id": "simplyswords:storms_edge",
                                "tag": {
                                    "Damage": 0
                                }
                            }
                        ]
```
### the result is this skeleton's mainhand item is bow and offhand item is simplyswords:storms_edge.
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/57590359/960c6710-64d1-4fdf-ac92-c9d38a9bf384)

### next  i try to write code in  gear_sets to let this skeleton's mainhand and offhand item are diamond sword.
```
{
	"weight": 0,
	"quality": 0,
	"mainhands": [
		{
			"weight": 1,
			"stack": {
				"item": "minecraft:diamond_sword"
			},
			"drop_chance": 0.5
		}
	],
	"offhands": [
		{
			"weight": 1,
			"stack": {
				"item": "minecraft:diamond_sword"
			},
			"drop_chance": 0.5
		}
	],
	"helmets": [
		{
			"weight": 1,
			"stack": {
				"item": "twilightforest:fiery_helmet"
			},
			"drop_chance": 0
		}
	],
	"chestplates": [
		{
			"weight": 1,
			"stack": {
				"item": "twilightforest:fiery_chestplate"
			},
			"drop_chance": 0
		}
	],
	"leggings": [
		{
			"weight": 1,
			"stack": {
				"item": "twilightforest:fiery_leggings"
			},
			"drop_chance": 0
		}
	],
	"boots": [
		{
			"weight": 1,
			"stack": {
				"item": "twilightforest:fiery_boots"
			},
			"drop_chance": 0
		}
	],
	"tags": []
}
```
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/57590359/5e56af87-ae88-41e7-be87-2d8d42cd2fa6)

### dropchange was successfully applied, but mainhand item still is bow

![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/57590359/fe508349-e8b9-4345-a12e-0ae6f44aa398)

### final  I changed the entity to a zombie it can take two diamond sword.
![image](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/57590359/b8afa680-4259-4c4a-a636-5800ed572dc2)

**Comment by Shadows-of-Fire** [comment]
Add `"finalize_spawn": false` to your wave entity objects, which will prevent addition of default equipment.

**Comment by YumisLink** [comment]
Thanks, spawned entities can now carry the correct custom weapons.
