### ISSUE TITLE
Enitty get removed from gateway

### ISSUE THREAD

**Issue by SpinoFTW** [Shadows-of-Fire/GatewaysToEternity#52]
hello i was playing epic fight and weapons of miracles and when i got to 4th wave of emeralfd grovethe gateway imploded becuase an entity was removed without being killed, i was wondering if this a bug[
![image_2024-05-28_224320745](https://github.com/Shadows-of-Fire/GatewaysToEternity/assets/72393243/dbeba71b-c77a-4751-93f7-fb77e5ad13a5)
](url)
https://mclo.gs/7OYoJsn this is log

**Comment by Milii20** [comment]
Hello!, by any chance, do you have Minecraft Comes Alive installed? i have an issue that may be related, when you have MCA installed, the moment the 4th wave starts, since it should be a zombie villager, MCA transforms (or deletes and replaces, not really sure) it into a MCA Zombie Villager, and that fails the emerald grove gateway, if that's the case with your game, maybe there is some way to check if MCA is installed and change the gateway? (actually i have no idea)

**Comment by Shadows-of-Fire** [comment]
In the general case, there is no way to know what has happened to the entity that gateways has marked as removed without being killed.  There's a flag you can set on the gateway that can be used to remove the rule on a per-gateway basis if there are consistent issues.

For the MCA case mentioned by @Milii20, MCA is responsible for firing the `LivingConversionEvent` for changing normal zombie villagers to MCA zombie villagers. Gateways listens to this event to handle conversions from one entity to another without losing the entity reference.

**Comment by border999** [comment]
> In the general case, there is no way to know what has happened to the entity that gateways has marked as removed without being killed. There's a flag you can set on the gateway that can be used to remove the rule on a per-gateway basis if there are consistent issues.
> 
> For the MCA case mentioned by @Milii20, MCA is responsible for firing the `LivingConversionEvent` for changing normal zombie villagers to MCA zombie villagers. Gateways listens to this event to handle conversions from one entity to another without losing the entity reference.

can you explain that flag part you mentioned? I'm having a similar issue. seems mostly related to entities getting converted in a way that the gate doesn't expect/understand so it flags them as left the area
