### ISSUE TITLE
[1.20.1] Crash gateways loot

### ISSUE THREAD

**Issue by jinkhya** [Shadows-of-Fire/GatewaysToEternity#53]
Hello, 
A player is playing on our atm9 to the sky server and it crashed when he used a gateway. 
Here's the crash log : https://gist.github.com/jinkhya/943fd7314719e5989cf54eb2d7d73338 

I see Ars nouveau is also involved in that log so if the issue is on that mod's end instead lemme know and I'll report it there :)

Thanks in advance,
Jin

**Comment by Shadows-of-Fire** [comment]
This looks to be caused by Ars, you'll have to report it there to get it resolved
