### ISSUE TITLE
Errored Gate Pearl?

### ISSUE THREAD

**Issue by reinhoc** [Shadows-of-Fire/GatewaysToEternity#54]
So, I got this description saying "Errored Gate Pearl, file a bug report detailing how you obtained this." I killed a mutant zombie which completed a quest "Slay Mutant Zombie" under the Lesser Evils questline playing the curseforge mod pack Cisco's Fantasy Medieval RPG [Ultimate]. If you have any more questions feel free to reach out

**Comment by Shadows-of-Fire** [comment]
You'll want to report this to the modpack you're playing rather than here, since the pearl you're getting is being added by them.
