### ISSUE TITLE
Entities being removed from gateways, compatability issues with Adaptive Performance Tweaks - Spawn

### ISSUE THREAD

**Issue by Dweblenod** [Shadows-of-Fire/GatewaysToEternity#57]
It appears that Adaptive Performance Tweaks - Spawn is removing entities that spawn from gateways in such a way that the gateway is not informed. This leads to waves that cannot be completed because there can be "1 remaining" despite none still existing

**Comment by Shadows-of-Fire** [comment]
There isn't really anything I can do to stop other mods from nuking entities, and there is no way for me to track them if they get removed in certain ways.  You should report this to APT and tell them to not remove entities being managed by a Gateway if at all possible.
