### ISSUE TITLE
Naming Gateways

### ISSUE THREAD

**Issue by GlitchedGekko** [Shadows-of-Fire/GatewaysToEternity#59]
I've managed to create a gateway and it functions as intended, I just have been unable to figure out how to have the gateways named as they are in the mod instead of being named their file path. I'd like to ask where I'm able to do that as I'm unable to find that in the documentation.

**Comment by meeprdib** [comment]
You need to create a resource pack for the items, following the filepath `assets/your_namespace/lang/en_us`

**Comment by Reaviik** [comment]
como exatamente eu faria isso, uma vez que todos os gateways tem o mesmo id. Consegue me mostrar um exemplo?
