### ISSUE TITLE
[v2.1.1] [Latest] Client cannot start-up. Possibly mod incompatiblity

### ISSUE THREAD

**Issue by Cixon** [Shadows-of-Fire/GatewaysToEternity#6]
**Context:** Installed the latest version with my mod-pack and noticed it would crash repeatably. No crash-report, just a log.
Can validate it's Gateways fault because issue stop persisting after removal.

[latest.log](https://github.com/Shadows-of-Fire/GatewaysToEternity/files/9441818/latest.log)

**Comment by Shadows-of-Fire** [comment]
`[29Aug2022 01:44:09.580] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed horseinboat.mixins.json:AbstractHorseMixin -> net.minecraft.world.entity.animal.horse.AbstractHorse: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException m_142469_()Lnet/minecraft/world/phys/AABB; in horseinboat.mixins.json:AbstractHorseMixin overrides a final method from net.minecraft.world.entity.Entity [MAIN Applicator Phase -> horseinboat.mixins.json:AbstractHorseMixin -> Apply Methods -> ()Lnet/minecraft/world/phys/AABB;:m_142469_ ->  -> Validate]
`

Nothing to do with GtE, appears to be something from a mod called `horseinboat`
