### ISSUE TITLE
Crashing when hovering over gateway tooltips in EMI (ATM10)

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/GatewaysToEternity#62]
Crashing with NoClassDefFoundError complaining about apothic attributes mod, when hovering over gateway tooltips in EMI. Happens on ATM10 0.57, gateways version 5.0.0

crash log here: https://mclo.gs/ii5RT6J
crash log from another player here: https://mclo.gs/id1hAxj

video on how to reproduce: https://i.imgur.com/CqXN5s0.mp4

**Comment by SiverDX** [comment]
you'll need to downgrade to https://www.curseforge.com/minecraft/mc-mods/apothic-attributes/files/5627172 for now
(and potentially downgrade neoforge version too)

gateways still uses some code which was removed from attributeslib (and integrated into neoforge itself)

**Comment by zanderkent** [comment]
The same thing happens in the Direwolf20 1.21 mod pack. Besides downgrading, do we have a potential fix in the works? Meaning, is this crash issue on the Gateways to Eternity side or a different side?

**Comment by Shadows-of-Fire** [comment]
This issue was resolved in Gateways 5.0.1

**Comment by zanderkent** [comment]
So all that's required is to upgrade to 5.0.1?
