### ISSUE TITLE
im not sure what to call this

### ISSUE THREAD

**Issue by superblast1** [Shadows-of-Fire/GatewaysToEternity#63]
![2024-10-23_13 24 58](https://github.com/user-attachments/assets/812c2f6f-89ad-42a7-b780-1c83939ce045)
![2024-10-23_13 24 58](https://github.com/user-attachments/assets/5bc9c1a2-532f-4226-a66e-9bfeed930812)

**Comment by superblast1** [comment]
![2024-10-23_13 25 02](https://github.com/user-attachments/assets/0c4bff22-6dbd-4b93-bf74-8a34342273f8)

**Comment by superblast1** [comment]
![2024-10-23_13 25 02](https://github.com/user-attachments/assets/a63a9b28-d6c5-4509-b875-b08944c8ed27)

**Comment by Shadows-of-Fire** [comment]
`Recipe By: Apotheotic Additions` - report it to them.
