### ISSUE TITLE
Custom Recipes not working

### ISSUE THREAD

**Issue by LgndTheDredgen** [Shadows-of-Fire/GatewaysToEternity#64]
I added a custom recipe for an undead gateway, the gateway works, but the recipe doesn't, I even copy pasted an existing one and as soon as I make changes it disables it in game, here's the example, any reason why it's not working?
{
  "type": "gateways:gate_recipe",
  "group": "gateways",
  "pattern": [
    "BRB",
    "RER",
    "BRB"
  ],
  "key": {
    "R": {
      "item": "minecraft:rotten_flesh"
    },
    "B": {
      "item": "minecraft:bone"
    },
    "E": {
      "item": "minecraft:eye_of_ender"
    }
    },
  "result": {
    "item": "gateways:gate_pearl"
  },
  "gateway": "gateways:basic/undead"
}

**Comment by RoyalReject** [comment]
What does your datapack look like? As the gateway id could be different based on your namespace. Attach the zip for you datapack if you could please

**Comment by LgndTheDredgen** [comment]
[Gateway Data Pack.zip](https://github.com/user-attachments/files/17741943/Gateway.Data.Pack.zip)

This isn't the exact resource pack since the original is MUCH bigger, but these are the exact files I'm using for the data of the custom gateways, there are also some files that are copied from the mod itself to help me out with the coding

**Comment by LgndTheDredgen** [comment]
> What does your datapack look like? As the gateway id could be different based on your namespace. Attach the zip for you datapack if you could please

[Gateway Data Pack.zip](https://github.com/user-attachments/files/17741992/Gateway.Data.Pack.zip)
This isn't the exact resource pack since the original is MUCH bigger, but these are the exact files I'm using for the data of the custom gateways, there are also some files that are copied from the mod itself to help me out with the coding

Edit: The recipe and the gateway is located in the basic folder as "undead". Because it's my first time I only made 1 custom gateway at the moment.

**Comment by meeprdib** [comment]
You can't load data via a resource pack

**Comment by LgndTheDredgen** [comment]
> You can't load data via a resource pack

oh, where would I make and add the data files to then?

**Comment by meeprdib** [comment]
You'd have to make a datapack, it's the same concept as a resource pack but with the Data files instead of the Assets files. Instead of putting a datapack in your resource packs folder, you're gonna want to put it in your world's "datapacks" folder, or, alternatively what I'd recommend, is to install [Paxi](https://www.curseforge.com/minecraft/mc-mods/paxi) to globally load your datapacks.

**Comment by LgndTheDredgen** [comment]
does global packs work too?

**Comment by meeprdib** [comment]
I converted what you send into a datapack, you're gonna wanna get rid of the "data" files in the zip you sent so only the assets remain in your resource pack



[LgndTheDredgen_gateways.zip](https://github.com/user-attachments/files/17742033/LgndTheDredgen_gateways.zip)


> does global packs work too?

Yes, Paxi is just my personal recommendation since I use it. It doesn't have anything over other loaders like Global Packs.

**Comment by LgndTheDredgen** [comment]
Okay great! I'll test it out again your way to see if it's functioning,
Just another question sorry to bother but what would be the nbt tag for each gateway pearl created be? Since I have a planned system to be a rare specific mob drop and craft upgraded versions using each other, like a tier 1 tier 2 system

**Comment by meeprdib** [comment]
> Okay great! I'll test it out again your way to see if it's functioning, Just another question sorry to bother but what would be the nbt tag for each gateway pearl created be? Since I have a planned system to be a rare specific mob drop and craft upgraded versions using each other, like a tier 1 tier 2 system

You can use mods like KubeJS, CraftTweaker, or Bookshelf to use their respective commands to get the NBT of the item in your hand. Their respective commands are `/kubejs hand`, `/ct hand`, and `/bookshelf hand SNBT`.

**Comment by LgndTheDredgen** [comment]
Amazing! Thank your for all the help, I've been enjoying this mod a lot!

**Comment by meeprdib** [comment]
no problem ^_^

**Comment by LgndTheDredgen** [comment]
got it working but still confused on how the nbt tags are added,
do you know if it's possible to use a specific gateway to craft into another one
Example: a slime gateway only can be used to make a blaze gateway in the crafting table
