### ISSUE TITLE
Can you use a specific gateway pearl as a recipe to craft a different gateway pearl?

### ISSUE THREAD

**Issue by LgndTheDredgen** [Shadows-of-Fire/GatewaysToEternity#65]
Like a tier system, can I per say, craft a slime pearl and then use that with blaze rods to then turn it into a blaze pearl?

I can't figure out how to use/input the correct NBT tag setup when adding the gateway pearl into a recipe

**Comment by Shadows-of-Fire** [comment]
Yes, using the same syntax you would for any other nbt based item input.  This isn't gateways-specific, so I won't handhold you to the solution.

**Comment by LgndTheDredgen** [comment]
> Yes, using the same syntax you would for any other nbt based item input. This isn't gateways-specific, so I won't handhold you to the solution.

Is it possible for just a short example?
Currently I have this and I couldn't make it work properly;
"A": {
      "item": "gateways:gate_pearl",
      "nbt": {
        "tag": {"gateway":"gateways:basic/slime"}
      }
Sorry I'm still new to all of this
