### ISSUE TITLE
[Suggestion] Entity Conversion detection for "Collective" Mods

### ISSUE THREAD

**Issue by border999** [Shadows-of-Fire/GatewaysToEternity#67]
![image](https://github.com/user-attachments/assets/b37d7e58-50a4-484d-8f6d-475470ce4100)
Do Gateways track on transformations caused any of these mods?

**Comment by Shadows-of-Fire** [comment]
Gateways handles all conversions that fire the `LivingConversionEvent.Post` event. Mods performing conversions are _responsible_ for firing this event, and if they do not, there is nothing else for Gateways to do.
