### ISSUE TITLE
[Feature Request] Naturally spawning gateways?

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Shadows-of-Fire/GatewaysToEternity#7]
They can spawn in the world near players at random intervals, with a _minimum_ of three in-game days in between each gateway.

Other ideas to compliment this:
- They only spawn at night
- No rewards for naturally spawned gateways outside of the drops from enemies you kill.
- They can only spawn in a spot where the sky is visible from above, to prevent getting ambushed in your base
- This whole feature can be toggled on and off, as it may not be for everyone

**Comment by Shadows-of-Fire** [comment]
I still have not put any time into adding this natively, but someone else has done it with a datapack https://www.planetminecraft.com/data-pack/gatewaybynight/

**Comment by konkerant0** [comment]
Making this a native feature or at least adding the link for the datapack in the mod page would be great. Gateways that spawn randomly and release monsters is a common trope in most korean novels and manwha, and there are also a lot of anime with similar plots. So if people knew that you can make portals spawn naturally, some anime or manwha based modpacks that use this mod might appear.

**Comment by Shadows-of-Fire** [comment]
No interest in doing this for the time being.
