### ISSUE TITLE
Additional gate pearls do not take effect

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadows-of-Fire/GatewaysToEternity#8]
Apotheosis adds a gate pearls to it's data pack, which works fine in single player, but doesn't work on servers
JEI can not be searched inside, and the gate pearls made after adding recipes can not be used

[latest.log](https://github.com/Shadows-of-Fire/GatewaysToEternity/files/9578188/latest.log)

**Comment by Shadows-of-Fire** [comment]
Specifically that pearl is broken because it uses the "rainbow" color, which is broken on servers.  This is a placebo bug that is already being handled.
